
package eai.msejdf.webServices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-12-06T16:34:21.341Z
 * Generated source version: 2.4.6
 */

@WebFault(name = "ConfigurationException", targetNamespace = "http://www.eai.org/msejdf")
public class ConfigurationException_Exception extends Exception {
    
    private eai.msejdf.webServices.ConfigurationException configurationException;

    public ConfigurationException_Exception() {
        super();
    }
    
    public ConfigurationException_Exception(String message) {
        super(message);
    }
    
    public ConfigurationException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ConfigurationException_Exception(String message, eai.msejdf.webServices.ConfigurationException configurationException) {
        super(message);
        this.configurationException = configurationException;
    }

    public ConfigurationException_Exception(String message, eai.msejdf.webServices.ConfigurationException configurationException, Throwable cause) {
        super(message, cause);
        this.configurationException = configurationException;
    }

    public eai.msejdf.webServices.ConfigurationException getFaultInfo() {
        return this.configurationException;
    }
}
