package eai.msejdf.webServices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-12-07T11:53:57.205Z
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://msejdf/EsbWebservice", name = "EsbWebservice")
@XmlSeeAlso({ObjectFactory.class})
public interface EsbWebservice {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersFollowingCompany", targetNamespace = "http://msejdf/EsbWebservice", className = "eai.msejdf.webServices.GetUsersFollowingCompany")
    @WebMethod
    @ResponseWrapper(localName = "getUsersFollowingCompanyResponse", targetNamespace = "http://msejdf/EsbWebservice", className = "eai.msejdf.webServices.GetUsersFollowingCompanyResponse")
    public java.util.List<eai.msejdf.webServices.User> getUsersFollowingCompany(
        @WebParam(name = "companyName", targetNamespace = "")
        java.lang.String companyName
    ) throws ESBWebserviceFaultESB;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserEmailCount", targetNamespace = "http://msejdf/EsbWebservice", className = "eai.msejdf.webServices.GetUserEmailCount")
    @WebMethod
    @ResponseWrapper(localName = "getUserEmailCountResponse", targetNamespace = "http://msejdf/EsbWebservice", className = "eai.msejdf.webServices.GetUserEmailCountResponse")
    public eai.msejdf.webServices.User getUserEmailCount(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId
    ) throws ESBWebserviceFaultESB;
}
