package eai.msejdf.webServices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-12-07T11:53:57.233Z
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "EsbWebserviceService", 
                  wsdlLocation = "file:/C:/Users/joaofcr/Desktop/MSE-EAI/Project3/WebBackOffice/src/EsbWebservice.wsdl",
                  targetNamespace = "http://msejdf/EsbWebservice") 
public class EsbWebserviceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://msejdf/EsbWebservice", "EsbWebserviceService");
    public final static QName EsbWebservicePort = new QName("http://msejdf/EsbWebservice", "EsbWebservicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/joaofcr/Desktop/MSE-EAI/Project3/WebBackOffice/src/EsbWebservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EsbWebserviceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/joaofcr/Desktop/MSE-EAI/Project3/WebBackOffice/src/EsbWebservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EsbWebserviceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EsbWebserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EsbWebserviceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EsbWebserviceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EsbWebserviceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EsbWebserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EsbWebservice
     */
    @WebEndpoint(name = "EsbWebservicePort")
    public EsbWebservice getEsbWebservicePort() {
        return super.getPort(EsbWebservicePort, EsbWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EsbWebservice
     */
    @WebEndpoint(name = "EsbWebservicePort")
    public EsbWebservice getEsbWebservicePort(WebServiceFeature... features) {
        return super.getPort(EsbWebservicePort, EsbWebservice.class, features);
    }

}
