package eai.msejdf.webServices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-12-06T16:34:21.403Z
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://www.eai.org/msejdf", name = "ListUserInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface ListUserInterface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserEmailCount", targetNamespace = "http://www.eai.org/msejdf", className = "eai.msejdf.webServices.GetUserEmailCount")
    @WebMethod
    @ResponseWrapper(localName = "getUserEmailCountResponse", targetNamespace = "http://www.eai.org/msejdf", className = "eai.msejdf.webServices.GetUserEmailCountResponse")
    public java.lang.Integer getUserEmailCount(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId
    ) throws ConfigurationException_Exception;

    @RequestWrapper(localName = "incrementUserEmailCountFromId", targetNamespace = "http://www.eai.org/msejdf", className = "eai.msejdf.webServices.IncrementUserEmailCountFromId")
    @WebMethod
    @ResponseWrapper(localName = "incrementUserEmailCountFromIdResponse", targetNamespace = "http://www.eai.org/msejdf", className = "eai.msejdf.webServices.IncrementUserEmailCountFromIdResponse")
    public void incrementUserEmailCountFromId(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId
    ) throws ConfigurationException_Exception;

    @RequestWrapper(localName = "incrementUserEmailCountFromList", targetNamespace = "http://www.eai.org/msejdf", className = "eai.msejdf.webServices.IncrementUserEmailCountFromList")
    @WebMethod
    @ResponseWrapper(localName = "incrementUserEmailCountFromListResponse", targetNamespace = "http://www.eai.org/msejdf", className = "eai.msejdf.webServices.IncrementUserEmailCountFromListResponse")
    public void incrementUserEmailCountFromList(
        @WebParam(name = "userId", targetNamespace = "")
        java.util.List<java.lang.Long> userId
    ) throws ConfigurationException_Exception;

    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "getUsersFollowingCompany", targetNamespace = "http://www.eai.org/msejdf", className = "eai.msejdf.webServices.GetUsersFollowingCompany")
    @WebMethod
    @ResponseWrapper(localName = "getUsersFollowingCompanyResponse", targetNamespace = "http://www.eai.org/msejdf", className = "eai.msejdf.webServices.GetUsersFollowingCompanyResponse")
    public java.util.List<eai.msejdf.webServices.User> getUsersFollowingCompany(
        @WebParam(name = "companyName", targetNamespace = "")
        java.lang.String companyName
    );
}
