package eai.msejdf.webServices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-12-06T16:34:21.450Z
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "WebServicesService", 
                  wsdlLocation = "http://127.0.0.1:8080/EJBServer/ListUserInterface?wsdl",
                  targetNamespace = "http://www.eai.org/msejdf") 
public class WebServicesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.eai.org/msejdf", "WebServicesService");
    public final static QName ListUserInterfacePort = new QName("http://www.eai.org/msejdf", "ListUserInterfacePort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/EJBServer/ListUserInterface?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebServicesService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/EJBServer/ListUserInterface?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebServicesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServicesService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebServicesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebServicesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ListUserInterface
     */
    @WebEndpoint(name = "ListUserInterfacePort")
    public ListUserInterface getListUserInterfacePort() {
        return super.getPort(ListUserInterfacePort, ListUserInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ListUserInterface
     */
    @WebEndpoint(name = "ListUserInterfacePort")
    public ListUserInterface getListUserInterfacePort(WebServiceFeature... features) {
        return super.getPort(ListUserInterfacePort, ListUserInterface.class, features);
    }

}
