//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.25 at 10:07:34 PM BST 
//


package eai.msejdf.data;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eai.msejdf.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Time_QNAME = new QName("", "time");
    private final static QName _LastCotation_QNAME = new QName("", "lastCotation");
    private final static QName _Address_QNAME = new QName("", "address");
    private final static QName _Sell_QNAME = new QName("", "sell");
    private final static QName _Website_QNAME = new QName("", "website");
    private final static QName _Minimum_QNAME = new QName("", "minimum");
    private final static QName _Maximum_QNAME = new QName("", "maximum");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _Variation_QNAME = new QName("", "variation");
    private final static QName _Purchase_QNAME = new QName("", "purchase");
    private final static QName _Quantity_QNAME = new QName("", "quantity");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eai.msejdf.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cotation }
     * 
     */
    public Cotation createCotation() {
        return new Cotation();
    }

    /**
     * Create an instance of {@link Company }
     * 
     */
    public Company createCompany() {
        return new Company();
    }

    /**
     * Create an instance of {@link Stock }
     * 
     */
    public Stock createStock() {
        return new Stock();
    }

    /**
     * Create an instance of {@link Stocks }
     * 
     */
    public Stocks createStocks() {
        return new Stocks();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "time")
    public JAXBElement<String> createTime(String value) {
        return new JAXBElement<String>(_Time_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lastCotation")
    public JAXBElement<BigDecimal> createLastCotation(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_LastCotation_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "address")
    public JAXBElement<String> createAddress(String value) {
        return new JAXBElement<String>(_Address_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sell")
    public JAXBElement<BigDecimal> createSell(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Sell_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "website")
    public JAXBElement<String> createWebsite(String value) {
        return new JAXBElement<String>(_Website_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "minimum")
    public JAXBElement<BigDecimal> createMinimum(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Minimum_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "maximum")
    public JAXBElement<BigDecimal> createMaximum(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Maximum_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "variation")
    public JAXBElement<BigDecimal> createVariation(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Variation_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "purchase")
    public JAXBElement<BigDecimal> createPurchase(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Purchase_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "quantity")
    public JAXBElement<BigInteger> createQuantity(BigInteger value) {
        return new JAXBElement<BigInteger>(_Quantity_QNAME, BigInteger.class, null, value);
    }

}
