//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2012.09.23 at 06:10:58 PM BST 
//

package eai.msejdf.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="stock" maxOccurs="unbounded" minOccurs="0">
*           &lt;complexType>
*             &lt;complexContent>
*               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                 &lt;sequence>
*                   &lt;element name="company">
*                     &lt;complexType>
*                       &lt;complexContent>
*                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                           &lt;sequence>
*                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                             &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                             &lt;element name="website" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
*                           &lt;/sequence>
*                         &lt;/restriction>
*                       &lt;/complexContent>
*                     &lt;/complexType>
*                   &lt;/element>
*                   &lt;element name="cotation">
*                     &lt;complexType>
*                       &lt;complexContent>
*                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                           &lt;sequence>
*                             &lt;element name="rate" type="{http://www.w3.org/2001/XMLSchema}float"/>
*                             &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}float"/>
*                             &lt;element name="maximum" type="{http://www.w3.org/2001/XMLSchema}float"/>
*                             &lt;element name="minimum" type="{http://www.w3.org/2001/XMLSchema}byte"/>
*                             &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
*                             &lt;element name="prevclose" type="{http://www.w3.org/2001/XMLSchema}float"/>
*                           &lt;/sequence>
*                         &lt;/restriction>
*                       &lt;/complexContent>
*                     &lt;/complexType>
*                   &lt;/element>
*                 &lt;/sequence>
*               &lt;/restriction>
*             &lt;/complexContent>
*           &lt;/complexType>
*         &lt;/element>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "stock"
})
@XmlRootElement(name = "stocks")
public class Stocks {

 protected List<Stocks.Stock> stock;

 /**
  * Gets the value of the stock property.
  * 
  * <p>
  * This accessor method returns a reference to the live list,
  * not a snapshot. Therefore any modification you make to the
  * returned list will be present inside the JAXB object.
  * This is why there is not a <CODE>set</CODE> method for the stock property.
  * 
  * <p>
  * For example, to add a new item, do as follows:
  * <pre>
  *    getStock().add(newItem);
  * </pre>
  * 
  * 
  * <p>
  * Objects of the following type(s) are allowed in the list
  * {@link Stocks.Stock }
  * 
  * 
  */
 public List<Stocks.Stock> getStock() {
     if (stock == null) {
         stock = new ArrayList<Stocks.Stock>();
     }
     return this.stock;
 }


 /**
  * <p>Java class for anonymous complex type.
  * 
  * <p>The following schema fragment specifies the expected content contained within this class.
  * 
  * <pre>
  * &lt;complexType>
  *   &lt;complexContent>
  *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *       &lt;sequence>
  *         &lt;element name="company">
  *           &lt;complexType>
  *             &lt;complexContent>
  *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *                 &lt;sequence>
  *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *                   &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *                   &lt;element name="website" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
  *                 &lt;/sequence>
  *               &lt;/restriction>
  *             &lt;/complexContent>
  *           &lt;/complexType>
  *         &lt;/element>
  *         &lt;element name="cotation">
  *           &lt;complexType>
  *             &lt;complexContent>
  *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *                 &lt;sequence>
  *                   &lt;element name="rate" type="{http://www.w3.org/2001/XMLSchema}float"/>
  *                   &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}float"/>
  *                   &lt;element name="maximum" type="{http://www.w3.org/2001/XMLSchema}float"/>
  *                   &lt;element name="minimum" type="{http://www.w3.org/2001/XMLSchema}byte"/>
  *                   &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
  *                   &lt;element name="prevclose" type="{http://www.w3.org/2001/XMLSchema}float"/>
  *                 &lt;/sequence>
  *               &lt;/restriction>
  *             &lt;/complexContent>
  *           &lt;/complexType>
  *         &lt;/element>
  *       &lt;/sequence>
  *     &lt;/restriction>
  *   &lt;/complexContent>
  * &lt;/complexType>
  * </pre>
  * 
  * 
  */
 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "", propOrder = {
     "company",
     "cotation"
 })
 public static class Stock {

     @XmlElement(required = true)
     protected Stocks.Stock.Company company;
     @XmlElement(required = true)
     protected Stocks.Stock.Cotation cotation;

     /**
      * Gets the value of the company property.
      * 
      * @return
      *     possible object is
      *     {@link Stocks.Stock.Company }
      *     
      */
     public Stocks.Stock.Company getCompany() {
         return company;
     }

     /**
      * Sets the value of the company property.
      * 
      * @param value
      *     allowed object is
      *     {@link Stocks.Stock.Company }
      *     
      */
     public void setCompany(Stocks.Stock.Company value) {
         this.company = value;
     }

     /**
      * Gets the value of the cotation property.
      * 
      * @return
      *     possible object is
      *     {@link Stocks.Stock.Cotation }
      *     
      */
     public Stocks.Stock.Cotation getCotation() {
         return cotation;
     }

     /**
      * Sets the value of the cotation property.
      * 
      * @param value
      *     allowed object is
      *     {@link Stocks.Stock.Cotation }
      *     
      */
     public void setCotation(Stocks.Stock.Cotation value) {
         this.cotation = value;
     }


     /**
      * <p>Java class for anonymous complex type.
      * 
      * <p>The following schema fragment specifies the expected content contained within this class.
      * 
      * <pre>
      * &lt;complexType>
      *   &lt;complexContent>
      *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      *       &lt;sequence>
      *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
      *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
      *         &lt;element name="website" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
      *       &lt;/sequence>
      *     &lt;/restriction>
      *   &lt;/complexContent>
      * &lt;/complexType>
      * </pre>
      * 
      * 
      */
     @XmlAccessorType(XmlAccessType.FIELD)
     @XmlType(name = "", propOrder = {
         "name",
         "address",
         "website"
     })
     public static class Company {

         @XmlElement(required = true)
         protected String name;
         @XmlElement(required = true)
         protected String address;
         @XmlElement(required = true)
         @XmlSchemaType(name = "anyURI")
         protected String website;

         /**
          * Gets the value of the name property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getName() {
             return name;
         }

         /**
          * Sets the value of the name property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setName(String value) {
             this.name = value;
         }

         /**
          * Gets the value of the address property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getAddress() {
             return address;
         }

         /**
          * Sets the value of the address property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setAddress(String value) {
             this.address = value;
         }

         /**
          * Gets the value of the website property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getWebsite() {
             return website;
         }

         /**
          * Sets the value of the website property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setWebsite(String value) {
             this.website = value;
         }

     }


     /**
      * <p>Java class for anonymous complex type.
      * 
      * <p>The following schema fragment specifies the expected content contained within this class.
      * 
      * <pre>
      * &lt;complexType>
      *   &lt;complexContent>
      *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      *       &lt;sequence>
      *         &lt;element name="rate" type="{http://www.w3.org/2001/XMLSchema}float"/>
      *         &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}float"/>
      *         &lt;element name="maximum" type="{http://www.w3.org/2001/XMLSchema}float"/>
      *         &lt;element name="minimum" type="{http://www.w3.org/2001/XMLSchema}byte"/>
      *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
      *         &lt;element name="prevclose" type="{http://www.w3.org/2001/XMLSchema}float"/>
      *       &lt;/sequence>
      *     &lt;/restriction>
      *   &lt;/complexContent>
      * &lt;/complexType>
      * </pre>
      * 
      * 
      */
     @XmlAccessorType(XmlAccessType.FIELD)
     @XmlType(name = "", propOrder = {
         "rate",
         "change",
         "maximum",
         "minimum",
         "quantity",
         "prevclose"
     })
     public static class Cotation {

         protected float rate;
         protected float change;
         protected float maximum;
         protected byte minimum;
         protected int quantity;
         protected float prevclose;

         /**
          * Gets the value of the rate property.
          * 
          */
         public float getRate() {
             return rate;
         }

         /**
          * Sets the value of the rate property.
          * 
          */
         public void setRate(float value) {
             this.rate = value;
         }

         /**
          * Gets the value of the change property.
          * 
          */
         public float getChange() {
             return change;
         }

         /**
          * Sets the value of the change property.
          * 
          */
         public void setChange(float value) {
             this.change = value;
         }

         /**
          * Gets the value of the maximum property.
          * 
          */
         public float getMaximum() {
             return maximum;
         }

         /**
          * Sets the value of the maximum property.
          * 
          */
         public void setMaximum(float value) {
             this.maximum = value;
         }

         /**
          * Gets the value of the minimum property.
          * 
          */
         public byte getMinimum() {
             return minimum;
         }

         /**
          * Sets the value of the minimum property.
          * 
          */
         public void setMinimum(byte value) {
             this.minimum = value;
         }

         /**
          * Gets the value of the quantity property.
          * 
          */
         public int getQuantity() {
             return quantity;
         }

         /**
          * Sets the value of the quantity property.
          * 
          */
         public void setQuantity(int value) {
             this.quantity = value;
         }

         /**
          * Gets the value of the prevclose property.
          * 
          */
         public float getPrevclose() {
             return prevclose;
         }

         /**
          * Sets the value of the prevclose property.
          * 
          */
         public void setPrevclose(float value) {
             this.prevclose = value;
         }

     }

 }

}
